version: '3'

services:
  sqlserver:
    container_name: icem-db
    image: liaisonintl/mssql-server-linux
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'r00t.R00T'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/opt/mssql
  web:
    container_name: icem-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver

volumes:
  sqlserver-data:
    driver: local